- hosts: all
  gather_facts: true
  tasks:
  - name: Collect the current NTP configuration
    ansible.utils.cli_parse:
      command: cat /etc/ntp.conf
      parser:
        name: ansible.netcommon.native
        template_path: "{{ playbook_dir }}/ntp_parser.yaml"
      set_fact: original_ntp_configuration

  - name: Compare the current and desired
    ansible.utils.fact_diff:
      before: "{{ ntp|ansible.utils.to_paths }}"
      after: "{{ original_ntp_configuration|ansible.utils.to_paths }}"
    register: ntp_difference
  
  - name: Correct NTP configuration
    when: ntp_difference.changed
    become: True
    block:
    - name: Push a corrected NTP conf file
      ansible.builtin.template:
        src: ntp.conf.j2
        dest: /etc/ntp.conf
        owner: root
        group: root
      vars:
        ntp_servers: "{{ ntp.servers }}"
    
    - name: Restart service ntpd
      ansible.builtin.service:
        name: ntpd
        state: restarted
    
    - name: Allow servers to syncronize (60s)
      ansible.builtin.pause: 
        seconds: 60
    
    - name: Collect the current NTP server statuses
      ansible.utils.cli_parse:
        command: ntpq -p
        parser:
          name: ansible.netcommon.native
          template_path: "{{ playbook_dir }}/ntp_parser.yaml"
        set_fact: current_ntp_status
    
    - name: Use a JSON schema to ensure no NTP servers are stratum 16 (unreachable)
      ansible.builtin.set_fact:
        unreachable_servers: "{{ current_ntp_status|ansible.utils.validate(criteria) }}"
      vars:
        criteria:
          type: object
          properties:
            statuses:
              type: array
              items:
                type: object
                properties:
                  stratum:
                    type: integer
                    not:
                      const: 16
                required:
                - stratum

    - name: Restore the original configuration if a server is failed (stratum 16)
      ansible.builtin.template:
        src: ntp.conf.j2
        dest: /etc/ntp.conf
        owner: root
        group: root
      vars:
        ntp_servers: "{{ original_ntp_configuration.servers }}"
      when: unreachable_servers
    
    - name: Fail the host to indicate unreachable servers were found and config restored
      ansible.builtin.fail:
        msg: "One or more ntp servers found with stratum 16: {{ unreachable_servers }}"
      when: unreachable_servers

      


    
    
      


     
